### ISSUE TITLE
text example does not work

### ISSUE THREAD

**Issue by georgey58** [makerstorage/Lightino#1]
Non existent dwellDelay() function in /examples/text2_interrupt/text2_interrupt.ino
font.h file doesnt compile for the board.

**Comment by makerstorage** [comment]
dwellDelay() is a procedure and coded inside the example.

https://github.com/makerstorage/Lightino/blob/master/examples/text2_interrupt/text2_interrupt.ino

line 184

**Comment by georgey58** [comment]
Apologies this is correct, It is the version on the lightino website than doesn't work.
